### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode-markdown-notebook#12]
Please add screenshots to README. This is a fast way to illustrate what is implemented.

I came here wanting to know if this supports running commands in blocks like:

<img width="89" alt="Screen Shot 2021-06-15 at 10 04 58" src="https://user-images.githubusercontent.com/382183/122066940-277fc800-cdc1-11eb-8531-156eae9bb379.png">

or what else it can do

**Comment by Gitleptune** [comment]
I second this, there is zero explanation of what it is and what it can do.

**Comment by roblourens** [comment]
There are now some screenshots. It's a very basic extension

**Comment by fulldecent** [comment]
Cool, thank you
