### ISSUE TITLE
Runme extension filling gaps in desired functionality

### ISSUE THREAD

**Issue by sourishkrout** [microsoft/vscode-markdown-notebook#17]
Hi there!

We more recently stumbled upon this extension and review its README.md as well as the issues, we've found that folks desire the ability to execute markdown fenced-code command blocks.

We have independently built the open source extension Runme (https://marketplace.visualstudio.com/items?itemName=stateful.runme). It's under active development & maintenance. We are also making strides to deliver a great UX/DX for runnable markdown documentation and welcome feedback.

https://github.com/stateful/vscode-runme

Wanted to reach out and see if we could work together and/or if you'd be open to either give Runme a shout out in Markdown Notebook's README or even consider recommending Runme in this extension's place. Let me know if there's a better way to get in touch with the maintainers and I'd be happy to do so.

Thanks!
Sebastian & The Runme Maintainers

**Comment by roblourens** [comment]
Cool extension, but vscode-markdown-notebook is a pretty basic extension with very little usage, I'm not really that interested in a collaboration.

**Comment by roblourens** [comment]
Cool idea though, let me know whether there's anything you need on the side of vscode notebook support.

**Comment by sourishkrout** [comment]
The fast response is much appreciated. I actually do have "feature requests". Can I email you, @roblourens? I promise I'll keep it short.
