### ISSUE TITLE
Disable automatic preview

### ISSUE THREAD

**Issue by qinting** [microsoft/vscode-markdown-notebook#20]
Hi, I have been enjoying using markdown-notebook, which is very convenient to organize codes and markdown documents in blocks. However, every time I create a new "Markdown" block, a preview tab would automatically be created. And if a new markdown document was opened by markdwon-notebook in vscode, multiple preview tabs would created automatically, which is very annoying. Could you please let me know how to disable the automatic preview function? I have tried everything I can found online, but all failed.

Thanks,
Tingting

**Comment by irvnriir** [comment]
This has global effect, but y can disable `markdown.extension.preview.autoShowPreviewToSide` if its enabled. Also, some other Extension could cause the preview to be auto opened.
